start cmd /k "cd services && python3 soa_service_inventario.py"
start cmd /k "cd services && python3 soa_service_usuarios.py"
start cmd /k "cd services && python3 soa_service_prestamos.py"
start cmd /k "cd services && python3 soa_service_multas.py"
start cmd /k "cd services && python3 soa_service_reportes.py"