start cmd /k "cd /d C:\Users\joaquin\Desktop\arq software\services && python3 soa_service_inventario.py"
start cmd /k "cd /d C:\Users\joaquin\Desktop\arq software\services && python3 soa_service_usuarios.py"
start cmd /k "cd /d C:\Users\joaquin\Desktop\arq software\services && python3 soa_service_prestamos.py"
start cmd /k "cd /d C:\Users\joaquin\Desktop\arq software\services && python3 soa_service_multas.py"
start cmd /k "cd /d C:\Users\joaquin\Desktop\arq software && python3 soa_client_menu.py"